version: '3'
services:
  legato_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: legato_db
      POSTGRES_HOST: database.legato
      POSTGRES_PORT: 5432
    ports:
      - "5431:5432"

networks:
  default:
    external:
      name: legato_default

