version: '3'
services:
  legato_server:
    env_file:
      - config/.env.compose
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "go", "run", "cmd/legato_server/main.go" ]
    environment:
      - MODE= prod
    ports:
      - "8080:8080"
    container_name: legato_server
    depends_on:
      - database
      - legato_scheduler
    deploy:
      restart_policy:
        condition: any

  legato_scheduler:
    env_file:
      - config/.env.compose
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "go", "run", "cmd/legato_scheduler/main.go" ]
    ports:
      - "8090:8090"
    container_name: legato_scheduler
    depends_on:
      - redis

  database:
    image: "postgres:14.2"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: legato
      POSTGRES_DB: legatodb
      POSTGRES_USER: legato
      POSTGRES_HOST: database.legato
      POSTGRES_PORT: 5432
    ports:
      - "5431:5432"
    container_name: legato_database

  redis:
    image: "redis:6.2.6"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: any

volumes:
  postgres_data:
  pgadmin:
  redis-data: