version: '3'
services:
  esid_server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/legato_server
  #    tests:
  #      build:
  #        context: .
  #        dockerfile: Dockerfile.dev
  #      volumes:
  #        - .:/go/src/legato_server
  #      command: ["go", "test", "./..."]
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: legato_db
      POSTGRES_HOST: database.legato
      POSTGRES_PORT: 5432
    ports:
      - "5431:5432"
