version: '3'
services:
  legato_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: [ "go", "run", "cmd/legato_server/main.go" ]
    env_file:
      - config/.env.compose
    ports:
      - "8080:8080"
    container_name: legato_server
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: any
        
  legato_scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: [ "go", "run", "cmd/legato_scheduler/main.go" ]
    ports:
      - "8090:8090"
    container_name: legato_scheduler
    depends_on:
      - redis

  database:
    image: "postgres:14.2"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: legato
      POSTGRES_DB: legatodb
      POSTGRES_USER: legato
      POSTGRES_HOST: database.legato
      POSTGRES_PORT: 5432
    ports:
      - "5431:5432"
    container_name: legato_database

  pgadmin:
    image: "dpage/pgadmin4:6"
    links:
      - database
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"

  redis:
    image: "redis:6.2.6"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  pgadmin:
