name: CI

on:
  push:
    branches:
      - develop
      - github-actions
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
#    env:
#      SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
#      SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
#      DISCORD_SECRET_BOT: ${{ secrets.DISCORD_SECRET_BOT }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Build the docker file
        run: |
          docker build -t legato_server .

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup
      - name: Build the docker-compose stack
        run: |
          docker-compose up -d 

      - name: Inspect images
        run: |
          docker image ls -a

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'

      # Run testing on the code
#      - name: Run testing
#        run: |
#          docker exec legato_server go test ./...

