name: CICD

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    #create required env file
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
        envkey_SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
        directory: ${{github.workspace}}/deployments/dev/
        file_name: web.env
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: LS
      run: ls -R
    # Setup 
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose-dev.yml up -d

    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
       time: '10s'

    - name: Check running containers
      run: docker ps
    
    # Run testing on the code
    - name: Run testing
      run: docker exec legato_server go test ./...
    
    # # Send slack notification
    # - name: Send slack notification
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
    #   if: always() # Pick up events even if the job fails or is canceled.

  # # The "deploy" workflow
  # deploy:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   needs: [build] # Only run this workflow when "build" workflow succeeds
  #   if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
  #   steps:
  #   - uses: actions/checkout@v2

  #   # Deploy to Docker registry
  #   - name: Deploy to Docker registry
  #     uses: docker/build-push-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       repository: wilsontanwm/gosimple
  #       tag_with_ref: true